### PR TITLE
Updated effect according to API changes

### PR DESCRIPTION
**Pull request by Lehonti**
https://github.com/PintaProject/Pinta/pull/1019

### CODE REVIEW

**Comment by cameronwhite** [comment]
Hmm, it seems like the CI builds didn't run, maybe because there hasn't been a commit in this repo for a while?

This didn't compile for me though - I think you'll need to update the git submodule for Pinta to build against the latest commit
```
NightVisionEffect.cs(52,30): error CS0508: 'NightVisionEffect.LaunchConfiguration()': return type must be 'void' to match overridden member 'BaseEffect.LaunchConfiguration()' [/Users/cameron/code/NightVisionEffect/NightVisionAddin/NightVisionAddin.csproj]
```

**Comment by Lehonti** [comment]
I just updated the submodule by running the following:

```
git clone --recurse-submodules https://github.com/Lehonti/NightVisionEffect_fork.git
cd .\NightVisionEffect_fork\
git submodule update --remote
git add .
git commit -m "update Pinta submodule"
git push origin
```

However, the build still fails.

**Comment by Lehonti** [comment]
I see that the problem is with the constructor, so I will check that.

**Comment by Lehonti** [comment]
I added the missing argument to the effect that is created inside `Render`. I hope this fixes it

**Comment by cameronwhite** [comment]
Yep looks good now - thanks!

**Pull request merged**
